---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - To-Do
      - HACK
      - Hack
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- ".*"
- node_modules/
- "**/reports/**/*"
- temp/
